# -*- coding: utf-8 -*-
"""Task_4_Predicting Insurance Claim Amounts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUxU204JPnwThsiC3M3Ow_K1r6lNXtpq

#Task 4: Predicting Insurance Claim Amounts

**Dependencies**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error

"""# OBJECTIVE

my objective is to predict insurance charges based on some personal details like age, BMI
"""

#uploding the csv
from google.colab import files
uploaded = files.upload()

"""**loading the dataset**"""

df = pd.read_csv("insurance.csv")
df.head()

"""# Exploring the data"""

df.info()

print(df.isnull().sum())  # null values
print({df.shape}) #shape of the dataset

"""**Descriptive statistics using describe function**"""

df.describe()

#To check the datatypes of the features
df.dtypes

"""#  Encode Categorical Variables"""

#encoding columns using label encoder
le = LabelEncoder()
# Male=1, Female=0
df['sex'] = le.fit_transform(df['sex'])
# Yes=1, No=0
df['smoker'] = le.fit_transform(df['smoker'])
# Region labels: 0–3
df['region'] = le.fit_transform(df['region'])

"""#VISUALIZATION OF KEY FEATURES"""

plt.figure(figsize=(5,3))
sns.scatterplot(data=df, x='bmi', y='charges', hue='smoker', palette='Set2')
plt.title("BMI vs Insurance Charges (Colored by Smoker)")
plt.show()

"""This graph shows that smokers with higher BMI tend to have significantly higher insurance charges compared to non-smokers. The cost impact of BMI is much more severe for smokers."""

plt.figure(figsize=(5,3))
sns.scatterplot(data=df, x='age', y='charges', hue='smoker', palette='coolwarm')
plt.title("Age vs Insurance Charges (Colored by Smoker)")
plt.show()

"""Insurance charges increase with age for all individuals, but the rise is much steeper for smokers. Older smokers pay the highest charges overall.


"""

plt.figure(figsize=(5,3))
sns.boxplot(data=df, x='smoker', y='charges', palette='pastel')
plt.xticks([0, 1], ['Non-Smoker', 'Smoker'])
plt.title("Insurance Charges by Smoking Status")
plt.show()

"""Smokers have a much higher median and wider spread of charges than non-smokers, confirming that smoking is a major factor driving up insurance costs.

**heatmap for correlation**
"""

plt.figure(figsize=(8,5))
sns.heatmap(df.corr(), annot=True, cmap='Blues')
plt.title("Feature Correlation Heatmap")
plt.show()

"""# Separate dataframe into separate object Features and Target"""

# Object for target variable
X = df.drop("charges", axis=1)
# object for input features
y = df["charges"]
#train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""# MODEL TRANING WITH LINEAR REGRESSION"""

model = LinearRegression()
model.fit(X_train, y_train)

# Predicting
y_pred = model.predict(X_test)

"""#  Evaluate model performance using MAE and RMSE"""

#Calculate Mean Absolute Error
mae = mean_absolute_error(y_test, y_pred)

#Calculate Root Mean Squared Error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

#printing them
print(f"MAE =  {mae:.2f}")
print(f"RMSE = {rmse:.2f}")

"""# CONCLUSION

The Linear Regression model predicted insurance charges with a MAE of 4186.51 and an RMSE of 5799.59, indicating moderate prediction error. Visual analysis showed that smoking, age, and BMI significantly influence charges, with smokers especially older or high BMI individuals incurring the highest costs. The model effectively highlights key factors affecting insurance pricing.
"""